### ISSUE TITLE
Can we enable serialisation of a Free Monad?

### ISSUE THREAD

**Issue by bblfish** [typelevel/spotted-leopards#3]
I have an interesting use case of Free Monads/Free applicatives that would when scalability becomes an issue require Free Monads and Free Applicatives, or equivalent framework (using perhaps effects) to make FreeMonads serialisable. I have kept some pointers of the discussion which lead me here in [this Twitter thread](https://twitter.com/bblfish/status/1133779901125996545).

Usually Free Monads are explained to be useful as they allow one to change interpreter. But it is also possible to allow them to be have many interpreters, one for each executed command.

I have implemented this on the [rww-play](https://github.com/read-write-web/rww-play) server following an initial implementation sketch written up by @betehess. The algebra is given in [LDPCommands.scala](https://github.com/read-write-web/rww-play/blob/dev/app/rww/ldp/LDPCommand.scala). Note that every LDPCommand has a URI. This allows the Akka interpreter of a FreeMonad constructed [in this test example](https://github.com/read-write-web/rww-play/blob/dev/test/ldp/LDRTestSuite.scala#L132) to route the FreeMonad datastructure depending on what the next instruction is as in one of these [Router Actors](https://github.com/read-write-web/rww-play/tree/dev/app/rww/ldp/actor/router). If the URI is local to the server the structure is sent as a message to [the actor that deals with that resource](https://github.com/read-write-web/rww-play/blob/dev/app/rww/ldp/actor/local/LDPCActor.scala#L174), or else to [a web actor that fetches it on the web](https://github.com/read-write-web/rww-play/blob/dev/app/rww/ldp/actor/remote/LDPWebActor.scala#L48) (could also be a cache actor).

This allows one to write generic scripts to fetch data on the web and act on the data received, without having to bother about implementation details.  But if one were to extend this to an actor system that spanned multiple actor instances potentially living on different servers, one would need I suppose to serialise these Free Monad/Applicative based scripts. This is not possible with cats now. 

Would this be possible in dotty? Or should I consider a completely different framework that could give me the same level of abstraction?

**Comment by tpolecat** [comment]
If you define `case class Free[F[_], A](resume: Either[A, F[Free[F, A]]])` then you have something you can serialize (if you can serialize `A`) and it will work just like `cats.free.Free` … but at the expense of  laziness and stack-safety which come from reifying `flatMap`, which is the root of your serialization problem. I don't know of a way you can have it both ways.

**Comment by bblfish** [comment]
Btw. In the [cats gitter channel](https://gitter.im/typelevel/cats?at=5ceec5e06bec22299e6f9cfe)  I was pointed to the [unison haskell like programming language](http://unisonweb.org/) which allows "all values including functions" to be serialisable. See [this discussion on their gitter channel](https://gitter.im/unisonweb/unison?at=5cefc93d38736d7e0ddb4e29). I am not sure how they do that, but it indicates that it can be done. 

That language is only 4 years old, and would be quite a shift and risk to move to.

**Comment by bblfish** [comment]
I am trying to understand how the FreeMonad creates the problem.

In one of [the test examples](https://github.com/read-write-web/rww-play/blob/68ce0dac96e4a9c12c796b4e70a09a08089f087f/test/ldp/LDRTestSuite.scala#L132) I build up my Free structure in the usual way:

```scala
"Test ACLs with ~ and ~> and <~ (tests bnode support too)" in {
    val nameEnum = for {
      wacLdr <- web(henryFoafWac)
      auth  <-  web.<~(LinkedDataResource(wacLdr.location,PointedGraph(henryFoaf,wacLdr.resource.graph)),wac.accessTo)()
      agentClass <-  web.~>(auth,wac.agentClass)()
      member <-  web.~>(agentClass,foaf.member)()
      name <- web.~>(member,foaf.name)()
    } yield {
      name
    }
}
```

(sorry for the cryptic operators, that was an early attempt I did a few years ago)

This creates a free data structure that is tied together with functions. Why would that data structure tied together with functions be more serialisable on the stack?

**Comment by bblfish** [comment]
ok, so it looks like functions are serialisable in Scala as they are objects. Spark makes a lot of this feature apparently (see [Serialization challenges with Spark and Scala](https://medium.com/onzo-tech/serialization-challenges-with-spark-and-scala-a2287cd51c54).
Scala proposed [SIP-21 on spores](https://docs.scala-lang.org/sips/spores.html) to help with serialisation issues, but it was [not much loved by Spark](https://www.reddit.com/r/scala/comments/702lct/what_ever_happened_to_sip21_aka_scala_spores/). Still Spores [got revived in nov 2016](https://www.scala-lang.org/blog/2016/11/30/spores-release.html). 

So I guess the reification of FlatMap, makes it impossible to know what needs to be serialised next and so would require the whole JVM to be serialised?

**Comment by bblfish** [comment]
So it looks that some upcoming cool features may be able to solve the Free stack problem.

**Comment by SethTisue** [comment]
> This is not possible with cats now

are you sure? as you point out,

> functions are serialisable in Scala

and also, I don't think this argument makes sense:

>  I guess the reification of FlatMap, makes it impossible to know what needs to be serialised next

as being able to serialize the function should cover it afaics.

it's an interesting question/discussion, but \<topic police>this repo doesn't seem like the place for it\</topic police> 👮‍♂️, as any possible connection to Dotty is seems quite speculative

**Comment by bblfish** [comment]
> > I guess the reification of FlatMap, makes it impossible to know what needs to be serialised next
> 
> as being able to serialize the function should cover it afaics. (both ends need to have the same classes on the classpath, but that's a usual constraint for this kind of thing.)

I was going on what @tpolecat wrote above

> but at the expense of laziness and stack-safety which come from reifying flatMap

So the problem seems to be that with current cats Free one either has a non serialisable structure or one rolls one's own and has one that risks running out of stack space. It seems that if one is looking to see what a future version improved version of cats could be it makes sense to investigate what would be needed. I can't tell in advance of asking the question if it is dotty that solves the problem or something else.

**Comment by bblfish** [comment]
Actually I just realised that a stack safe version of Free as mentioned by @tpolecat 

> If you define case class Free[F[_], A](resume: Either[A, F[Free[F, A]]]) then you have something you can serialize (if you can serialize A) and it will work just like cats.free.Free

would actually work for my use case as each frame of the stack is executed by a different actor on a different stack. So as long as the functions linking to Free Monads don't use up a lot of stack, which is something one can warn people about, then things should be ok.

**Comment by jdegoes** [comment]
> If you define case class Free[F[_], A](resume: Either[A, F[Free[F, A]]]) then you have something you can serialize (if you can serialize A) and it will work just like cats.free.Free

Unfortunately this won't work. Cats Free doesn't require that `F[_]` be a functor, whereas the above (classic) definition of `Free` _does_ have this requirement. So when you have `F[_]` terms that produce information, you'll end up embedding continuations in those operations:

e.g.:

```scala
sealed trait ConsoleF[+A]
final case class ReadLine[+A](next: String => A) extends ConsoleF[A]
final case class WriteLine[+A](line: String, next: A) extends ConsoleF[A]
```

Any structure with the power of `Monad` will end up storing a continuation, in one form or another: in this case, either in the `F[_]` or in the `Free`.

That said, you can serialize functions "well enough" to make a billion dollar industry (Spark), and fundamentally, serializing `Free` is all about serializing functions. The main problems (aside from instability of the protocol) are the random objects that will be accidentally captured in the closures, some of which won't be sanely serializable (e.g. a thread pool, an http connection pool, a local cache).

If your code accesses all resources (i.e. non-data) through a reader monad (like [ZIO](https://zio.dev) Environment encourages), however, then you can shift these "non-serializable dependencies" onto the remote node, which can satisfy them after deserialization. Now the compiler can't help you do the right thing, but it provides a path toward reasonable serialization.

Even without that, despite its pains, Spark shows serialization can be useful (i.e. solve business problems), with a level of pain that comes with the territory.

**Comment by tpolecat** [comment]
That's a very good point. Your underlying functor must be serializable. So it would work for `Free[List, ?]` for instance but won't work in general. In particular the GADT-to-DSL pattern won't work because you'll need to encode the continuation as @jdegoes noted, or you'll need to use a free functor which does the same thing.

**Comment by bblfish** [comment]
Btw, looking at ZIO over the past day, I noticed that [ZIO is `Serializeable`](https://github.com/zio/zio/blob/32a9b8c48de4f6107f3751cb33835695138414cf/core/shared/src/main/scala/scalaz/zio/ZIO.scala#L68)

```scala
sealed trait ZIO[-R, +E, +A] extends Serializable { self => ... }
```

As I understand ZIO is a [Rotated](http://degoes.net/articles/rotating-effects#typesafe) Free Monad with a couple of other Monads built in for efficiency. 

So yes, my intention is perhaps not to build the full serialisation infrastructure to start with, but to make sure that if I get some funds to build it out, I am sure that I don't have to rearchitect the platform from scratch, as well as to get an idea of how complicated it may end up being before embarking on such a project.
