### ISSUE TITLE
crosslink with Travis Brown's efforts?

### ISSUE THREAD

**Issue by SethTisue** [typelevel/spotted-leopards#8]
it sounds like anyone interested in this repo would also want to check out whatever @travisbrown has been up to: https://twitter.com/travisbrown/status/1201797119176323072

**Comment by djspiewak** [comment]
Worth noting that Travis' efforts seem mostly aimed at making Cats cross-build, which is incredibly important and worthwhile in and of itself. The purpose of *this* repo is a bit more of a reimagining of Cats in a Dotty-only context. Agreed on the cross-linking, just wanted to clarify how the objectives are different.

**Comment by SethTisue** [comment]
https://twitter.com/travisbrown/status/1274029171086368774 🎉
